### ISSUE TITLE
Version in dependency

### ISSUE THREAD

**Issue by legarconjoure** [allure-examples/allure-cucumber-jvm-example#1]
Hi,

The version in dependency section "1.4.5" for allure-cucumber-jvm-adaptor does not work for me. When I change it to "1.0" it works fine.

Has the 1.4.5 been pushed to any repository? In http://repo.maven.apache.org/ I can only find the latest version as "1.0".

**Comment by clicman** [comment]
After adaptor became stable, I was dropped version number to 1.0. So it is lastest version for now. Today I will change version in example. Sorry for confusion. :)

**Comment by clicman** [comment]
Done.

**Comment by legarconjoure** [comment]
Thanks!
